module.exports = `CREATE TABLE IF NOT EXISTS profile_avatars (
 user_id INT PRIMARY KEY,
 image MEDIUMBLOB NOT NULL,
 content_type VARCHAR(30) NOT NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)`;
